### ISSUE TITLE
Task load issue

### ISSUE THREAD

**Issue by roporter** [roporter/UCSD-Infinidat#1]
2016-05-05 14:38:00,114 [main] ERROR initFeature(CustomModule.java:208) - ERROR:  registering components for feature infinidat
java.lang.Exception: Workflow Task definition already exists: Handler Type - Delete Volume
	at com.cloupia.service.cIM.inframgr.CustomFeatureRegistry.registerWorkflowTask(CustomFeatureRegistry.java:107)
	at com.cloupia.service.cIM.inframgr.AbstractCloupiaModule.registerTask(AbstractCloupiaModule.java:137)
	at com.cloupia.service.cIM.inframgr.AbstractCloupiaModule.registerTasks(AbstractCloupiaModule.java:93)
	at com.cloupia.service.cIM.inframgr.AbstractCloupiaModule.registerComponents(AbstractCloupiaModule.java:63)
	at com.cloupia.service.cIM.inframgr.CustomModule.initFeature(CustomModule.java:206)
	at com.cloupia.service.cIM.inframgr.FeatureContainer.initFeatures(FeatureContainer.java:229)
	at com.cloupia.service.cIM.inframgr.FeatureContainer.initFeatures(FeatureContainer.java:203)
	at com.cloupia.service.cIM.inframgr.InfraMgrImpl.initService(InfraMgrImpl.java:775)
	at com.cloupia.service.cIM.inframgr.APIProvider.initService(APIProvider.java:222)
	at com.cloupia.fw.services.provider.ServiceProvider.init(ServiceProvider.java:520)
	at com.cloupia.fw.services.provider.ServiceProvider.init(ServiceProvider.java:293)
	at com.cloupia.fw.services.provider.ServiceProvider.init(ServiceProvider.java:267)
	at com.cloupia.service.cIM.inframgr.InfraMgrMain.main(InfraMgrMain.java:176)

**Comment by roporter** [comment]
AbstractTask task1 = new INFINIDATcreatePoolTask();
		AbstractTask task2 = new INFINIDATcreateVolumeTask();
		AbstractTask task3 = new INFINIDATcreateHostTask();
		AbstractTask task4 = new INFINIDATeditPoolTask();
		AbstractTask task5 = new INFINIDATeditVolumeTask();
		AbstractTask task6 = new INFINIDATeditHostTask();
		AbstractTask task7 = new INFINIDATdeletePoolTask();

Succeed

**Comment by roporter** [comment]
Solved - My poorly named task was conflicting with another vendors poorly named task :-)  Lesson learned, make your files, tasks, classes etc as unique as possible!
